apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: flask
spec:
  selector:
    app: flask
  clusterIP: None  # k8s Headless Service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
