apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  namespace: flask-backend
spec:
  selector:
    app: flask-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
