apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 338456725408.dkr.ecr.ap-northeast-1.amazonaws.com/flask:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_URL
              value: http://flask-backend.flask-backend:5000/messages
            - name: AWS_DEFAULT_REGION
              value: ap-northeast-1
            - name: DYNAMODB_TABLE_NAME
              value: messages

  selector:
    matchLabels:
      app: flask-app
