apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: flask
      containers:
      - name: flask
        image: 338456725408.dkr.ecr.ap-northeast-1.amazonaws.com/flask:2022-07-11H12.08.57-34e1d2b
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: AWS_DEFAULT_REGION
          value: ap-northeast-1
        - name: DYNAMODB_TABLE_NAME
          value: messages-prd
  selector:
    matchLabels:
      app: flask
